-- DELETE FAKE/FABRICATED IPOs BATCH 1 of 8
-- Removes 100 non-existent/fabricated IPO entries
-- Run in Supabase SQL Editor AFTER running all upsert batches

BEGIN;

DELETE FROM public.ipos
WHERE slug IN ('gng-electronics-limited-ipo', 'highway-infrastructure-limited-ipo', 'regaal-resources-limited-ipo', 'urban-company-limited-ipo', 'vms-tmt-ltd-ipo', 'tenneco-clean-air-india-limited-ipo', 'meesho-limited-ipo', 'central-mine-planning-ipo-copy-1773813197995', 'boss-packaging-solutions-ipo', 'kody-technolab-ipo', 'gunsindoor-softtech-ipo', 'trust-freight-logistics-ipo', 'vvip-infratech-ipo', 'paramount-speciality-forgings-ipo', 'shree-karni-fabcom-ipo', 'royal-sense-ipo', 'euphoria-infotech-ipo', 'harshdeep-hortico-ipo', 'alpex-solar-ipo', 'rudra-gas-enterprise-ipo', 'polysil-irrigation-systems-ipo', 'purv-flexipack-ipo', 'mvk-agro-food-product-ipo', 'sd-retail-ipo', 'ganesh-green-bharat-ipo', 'effwa-infra-and-research-ipo', 'ambey-laboratories-ipo', 'divine-power-energy-ipo', 'petro-carbon-and-chemicals-ipo', 'shivalic-power-control-ipo', 'akiko-global-services-ipo', 'falcon-technoprojects-india-ipo', 'zeal-global-services-ipo', 'vinyas-innovative-technologies-ipo', 'kahan-packaging-ipo', 'aether-industries-ipo', 'blue-jet-healthcare-ipo', 'cyient-dlm-ipo', 'ideaforge-technology-ipo', 'signatureglobal-ipo', 'yatra-online-ipo', 'zaggle-prepaid-ocean-services-ipo', 'samhi-hotels-ipo', 'plaza-wires-ipo', 'valiant-laboratories-ipo', 'updater-services-ipo', 'manning-logistics-ipo', 'apex-ecotech-ipo', 'bhandari-hosiery-exports-ipo', 'capital-numbers-infotech-ipo', 'delta-autocorp-ipo', 'enviro-infratech-ipo', 'fast-track-logistics-ipo', 'green-leaf-energy-ipo', 'hitech-machinery-ipo', 'innovative-automation-ipo', 'jupiter-solar-power-ipo', 'kothari-petrochemicals-ipo', 'lotus-dairy-products-ipo', 'marvel-decor-ipo', 'nexus-retail-stores-ipo', 'omni-hospitals-ipo', 'pacific-pipes-and-tubes-ipo', 'quantum-robotics-and-tech-ipo', 'radhika-jewelcraft-ipo', 'suntech-energy-solutions-ipo', 'tech-pulse-saas-ipo', 'ultra-pack-containers-ipo', 'vision-pharma-labs-ipo', 'wind-solar-kraft-ipo', 'xcell-biotech-enzymes-ipo', 'yield-fintech-solutions-ipo', 'zenith-polymers-ipo', 'ambica-specialty-steels-ipo', 'bharat-clean-energy-tech-ipo', 'cyber-shield-systems-ipo', 'deep-sea-marine-logistics-ipo', 'evergreen-agri-inputs-ipo', 'future-ev-mobility-ipo', 'global-defense-electronics-ipo', 'hyperion-solar-glass-ipo', 'infra-prime-bridge-build-ipo', 'zen-cardiovascular-devices-ipo', 'astra-precision-components-ipo', 'bravura-power-cables-ipo', 'celeste-organic-fine-chem-ipo', 'dura-tech-fasteners-ipo', 'echo-electronics-assembly-ipo', 'finedge-software-solutions-ipo', 'genesis-agri-products-ipo', 'helios-clean-power-ipo', 'impulse-logistics-services-ipo', 'jyoti-bio-energy-ipo', 'kaveri-infra-projects-ipo', 'matrix-pharma-formulations-ipo', 'navkar-urban-structures-ipo', 'omega-precision-tools-ipo', 'pinnacle-renewable-power-ipo', 'qualitas-engineering-ipo', 'radiant-solar-infra-ipo');

COMMIT;
