-- ==============================================================================
-- FIX MISSING FIELDS FOR EXISTING DATABASE IPOS (e.g. Azad Engineering, Cello World, etc.)
-- ==============================================================================

-- 1. Azad Engineering (azad-engineering)
UPDATE public.ipos SET
  listing_exchange = 'NSE, BSE',
  exchange = 'NSE, BSE',
  retail_min_lots = 1,
  retail_min_shares = 28,
  retail_min_amount = 14672,
  retail_max_lots = 13,
  retail_max_shares = 364,
  retail_max_amount = 190736,
  shni_lots = 14,
  shni_shares = 392,
  shni_amount = 205408,
  shni_max_lots = 68,
  shni_max_shares = 1904,
  shni_max_amount = 997696,
  bhni_lots = 69,
  bhni_shares = 1932,
  bhni_amount = 1012368,
  reservation_qib = '50%',
  reservation_nii = '15%',
  reservation_rii = '35%',
  company_address = 'Plot No. 90/C, 90/D, Phase I, I.D.A. Jeedimetla, Hyderabad 500055, Telangana',
  company_phone = '+91-40-2309-7000',
  company_email = 'cs@azad.in',
  company_website = 'https://www.azad.in',
  registrar_phone = '+91-40-6716-2222',
  registrar_email = 'azad.ipo@kfintech.com',
  registrar_website = 'https://ris.kfintech.com',
  drhp_link = 'https://www.sebi.gov.in/filings/approved-option/sep-2023/azad-engineering-limited-drhp.html',
  rhp_link = 'https://www.sebi.gov.in/filings/approved-option/dec-2023/azad-engineering-limited-rhp.html',
  allotment_link = 'https://ris.kfintech.com/ipostatus',
  listing_gain_percent = 37.40
WHERE slug = 'azad-engineering';

-- 2. Cello World (cello-world)
UPDATE public.ipos SET
  listing_exchange = 'NSE, BSE',
  exchange = 'NSE, BSE',
  retail_min_lots = 1,
  retail_min_shares = 23,
  retail_min_amount = 14881,
  retail_max_lots = 13,
  retail_max_shares = 299,
  retail_max_amount = 193453,
  shni_lots = 14,
  shni_shares = 322,
  shni_amount = 208334,
  shni_max_lots = 67,
  shni_max_shares = 1541,
  shni_max_amount = 997027,
  bhni_lots = 68,
  bhni_shares = 1564,
  bhni_amount = 1011908,
  reservation_qib = '50%',
  reservation_nii = '15%',
  reservation_rii = '35%',
  company_address = '550, Cello House, Subhash Nagar, Kanjurmarg East, Mumbai 400042',
  company_phone = '+91-22-2578-0414',
  company_email = 'info@celloworld.com',
  company_website = 'https://www.celloworld.com',
  registrar_phone = '+91-22-4918-6270',
  registrar_email = 'cello.ipo@linkintime.co.in',
  registrar_website = 'https://linkintime.co.in',
  listing_gain_percent = 27.87
WHERE slug = 'cello-world';

-- 3. RBZ Jewellers (rbz-jewellers)
UPDATE public.ipos SET
  listing_exchange = 'NSE, BSE',
  exchange = 'NSE, BSE',
  retail_min_lots = 1,
  retail_min_shares = 150,
  retail_min_amount = 15000,
  retail_max_lots = 13,
  retail_max_shares = 1950,
  retail_max_amount = 195000,
  shni_lots = 14,
  shni_shares = 2100,
  shni_amount = 210000,
  shni_max_lots = 66,
  shni_max_shares = 9900,
  shni_max_amount = 990000,
  bhni_lots = 67,
  bhni_shares = 10050,
  bhni_amount = 1005000,
  reservation_qib = '50%',
  reservation_nii = '15%',
  reservation_rii = '35%',
  company_address = 'Block D, Mondeal Retail Park, Near Rajpath Club, SG Highway, Ahmedabad 380054',
  company_phone = '+91-79-2686-2001',
  company_email = 'cs@rbzjewellers.com',
  company_website = 'https://www.rbzjewellers.com',
  registrar_phone = '+91-79-2646-5179',
  registrar_email = 'ahmedabad@bigshareonline.com',
  registrar_website = 'https://www.bigshareonline.com',
  listing_gain_percent = 0.00
WHERE slug = 'rbz-jewellers';
