-- ============================================================
-- MASTER CLEANUP: DELETE ALL NON-VERIFIED IPOs
-- This removes every row in public.ipos whose slug is NOT
-- in our 105 verified real IPO list.
-- Run this ONCE in Supabase SQL Editor.
-- ============================================================

BEGIN;

DELETE FROM public.ipos
WHERE slug NOT IN (
  'tata-technologies',
  'ireda',
  'inox-india',
  'doms-industries',
  'azad-engineering',
  'cello-world',
  'honasa-consumer-mamaearth',
  'fedbank-financial-services',
  'flair-writing-industries',
  'gandhar-oil-refinery',
  'esaf-small-finance-bank',
  'protean-egov-technologies',
  'ask-automotive',
  'jyoti-cnc-automation',
  'medi-assist-healthcare',
  'epack-durable',
  'nova-agritech',
  'bls-e-services',
  'apeejay-surrendra-park-hotels',
  'rashi-peripherals',
  'jana-small-finance-bank',
  'capital-small-finance-bank',
  'entero-healthcare',
  'vibhor-steel-tubes',
  'juniper-hotels',
  'platinum-industries',
  'exicom-tele-systems',
  'mukka-proteins',
  'rk-swamy',
  'jg-chemicals',
  'gopal-snacks',
  'popular-vehicles',
  'krystal-integrated-services',
  'srm-contractors',
  'bharti-hexacom',
  'jnk-india',
  'indegene-limited',
  'tbo-tek',
  'go-digit-general-insurance',
  'awfis-space-solutions',
  'kronox-lab-sciences',
  'le-travenues-technology-ixigo',
  'dee-development-engineers',
  'akme-fintrade',
  'stanley-lifestyles',
  'vraj-iron-and-steel',
  'bansal-wire-industries',
  'emcure-pharmaceuticals',
  'sanstar-limited',
  'akums-drugs-and-pharmaceuticals',
  'ceigall-india',
  'ola-electric-mobility',
  'brainbees-solutions-firstcry',
  'unicommerce-esolutions',
  'interarch-building-products',
  'orient-technologies',
  'premier-energies',
  'baazar-style-retail',
  'gala-precision-engineering',
  'kross-limited',
  'tolins-tyres',
  'bajaj-housing-finance',
  'p-n-gadgil-jewellers',
  'western-carriers-india',
  'arkade-developers',
  'northern-arc-capital',
  'manba-finance',
  'krn-heat-exchanger',
  'garuda-construction',
  'hyundai-motor-india',
  'deepak-builders-and-engineers',
  'waaree-energies',
  'godavari-biorefineries',
  'afcons-infrastructure',
  'sagility-india',
  'acme-solar-holdings',
  'swiggy-limited',
  'ntpc-green-energy',
  'standard-glass-lining-ipo',
  'gng-electronics-ipo',
  'highway-infrastructure-ipo',
  'regaal-resources-ipo',
  'shringar-house-of-mangalsutra-ipo',
  'vms-tmt-ipo',
  'rubicon-research-ipo',
  'corona-remedies-limited-ipo',
  'shree-ram-twistex-ipo',
  'pngs-reva-diamond-jewellery-limited-ipo',
  'sedemac-mechatronics-ipo',
  'skyways-air-services-limited-ipo',
  'tenneco-clean-air-ipo',
  'sbi-funds-management-limited-ipo',
  'central-mine-planning-ipo',
  'tac-infosec-ipo',
  'kay-cee-energy-and-infra-ipo',
  'creative-graphics-solutions-ipo',
  'indian-phosphate-ipo',
  'resourceful-automobile-ipo',
  'max-exposure-ipo',
  'macobs-technologies-ipo',
  'urban-company-ipo',
  'hdb-financial-services-ipo',
  'meesho-ipo',
  'tata-capital-ipo',
  'lg-electronics-india-ipo'
);

-- Verify: after this, only 105 rows should remain
SELECT COUNT(*) AS remaining_ipo_count FROM public.ipos;

COMMIT;
