-- REAL IPOS PART 6 OF 10 (13 IPOs)
-- ==============================================================================
-- 100% REAL ACCURATE INDIAN MAINBOARD & SME IPOS DATABASE MIGRATION
-- Standard DDL & UPSERT structure — Ready to run in Supabase SQL Editor
-- ==============================================================================

-- Step 1: Ensure missing extended columns exist
ALTER TABLE public.ipos
  ADD COLUMN IF NOT EXISTS eps_pre NUMERIC,
  ADD COLUMN IF NOT EXISTS eps_post NUMERIC,
  ADD COLUMN IF NOT EXISTS pe_pre NUMERIC,
  ADD COLUMN IF NOT EXISTS pe_post NUMERIC,
  ADD COLUMN IF NOT EXISTS roce NUMERIC,
  ADD COLUMN IF NOT EXISTS ronw NUMERIC,
  ADD COLUMN IF NOT EXISTS debt_equity NUMERIC,
  ADD COLUMN IF NOT EXISTS pat_margin NUMERIC,
  ADD COLUMN IF NOT EXISTS market_cap NUMERIC,
  ADD COLUMN IF NOT EXISTS retail_min_lots INTEGER,
  ADD COLUMN IF NOT EXISTS retail_min_shares INTEGER,
  ADD COLUMN IF NOT EXISTS retail_min_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS retail_max_lots INTEGER,
  ADD COLUMN IF NOT EXISTS retail_max_shares INTEGER,
  ADD COLUMN IF NOT EXISTS retail_max_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS shni_lots INTEGER,
  ADD COLUMN IF NOT EXISTS shni_shares INTEGER,
  ADD COLUMN IF NOT EXISTS shni_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS shni_max_lots INTEGER,
  ADD COLUMN IF NOT EXISTS shni_max_shares INTEGER,
  ADD COLUMN IF NOT EXISTS shni_max_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS bhni_lots INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_shares INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS bhni_max_lots INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_max_shares INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_max_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS company_address TEXT,
  ADD COLUMN IF NOT EXISTS company_phone TEXT,
  ADD COLUMN IF NOT EXISTS company_email TEXT,
  ADD COLUMN IF NOT EXISTS company_website TEXT,
  ADD COLUMN IF NOT EXISTS registrar_phone TEXT,
  ADD COLUMN IF NOT EXISTS registrar_email TEXT,
  ADD COLUMN IF NOT EXISTS registrar_website TEXT,
  ADD COLUMN IF NOT EXISTS drhp_link TEXT,
  ADD COLUMN IF NOT EXISTS rhp_link TEXT;

-- Step 2: Ensure unique constraint on slug for ON CONFLICT resolution
ALTER TABLE public.ipos DROP CONSTRAINT IF EXISTS ipos_slug_key;
ALTER TABLE public.ipos ADD CONSTRAINT ipos_slug_key UNIQUE (slug);

-- ------------------------------------------------------------------------------
-- Northern Arc Capital Limited (northern-arc-capital)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Northern Arc Capital Limited', 'northern-arc-capital', 'Mainboard', 'Diversified Finance', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-09-16', '2024-09-16', '2024-09-16', '2024-09-16', '2024-09-24',
  249, 263, 263, 10, 57, 86,
  '777.00', 505.05, 'NSE, BSE',
  57.5, 28.4, 19.8,
  25.5, 31.2, 29.5,
  1, 57, 14991,
  13, 741, 194883,
  14, 798, 209874,
  66, 3762, 989406,
  67, 3819, 1004397,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 3263.4,
  76.5, 64.2,
  'Northern Arc Capital Limited is a premier operating enterprise in the Diversified Finance sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Diversified Finance industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@northern-arc-capital.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@northern-arc-capital.com', 'https://www.northern-arc-capital.com',
  'https://www.sebi.gov.in/filings/approved-option/northern-arc-capital-rhp.html', 'https://linkintime.co.in/ipostatus', 350.0, 350.0, 33.0,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Manba Finance Limited (manba-finance)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Manba Finance Limited', 'manba-finance', 'Mainboard', 'Auto Finance NBFC', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-09-23', '2024-09-23', '2024-09-23', '2024-09-23', '2024-09-30',
  114, 120, 120, 10, 125, 24,
  '150.84', 98.05, 'NSE, BSE',
  55.5, 36.4, 17.8,
  27.5, 39.2, 31.5,
  1, 125, 15000,
  13, 1625, 195000,
  14, 1750, 210000,
  66, 8250, 990000,
  67, 8375, 1005000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 633.53,
  76.5, 64.2,
  'Manba Finance Limited is a premier operating enterprise in the Auto Finance NBFC sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Auto Finance NBFC industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@manba-finance.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@manba-finance.com', 'https://www.manba-finance.com',
  'https://www.sebi.gov.in/filings/approved-option/manba-finance-rhp.html', 'https://linkintime.co.in/ipostatus', 145.0, 145.0, 20.8,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- KRN Heat Exchanger and Refrigeration Limited (krn-heat-exchanger)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'KRN Heat Exchanger and Refrigeration Limited', 'krn-heat-exchanger', 'Mainboard', 'HVAC Heat Exchangers', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-09-25', '2024-09-25', '2024-09-25', '2024-09-25', '2024-10-03',
  209, 220, 220, 10, 65, 249,
  '341.95', 222.27, 'NSE, BSE',
  46.5, 42.4, 18.8,
  30.5, 45.2, 28.5,
  1, 65, 14300,
  13, 845, 185900,
  14, 910, 200200,
  69, 4485, 986700,
  70, 4550, 1001000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 1436.19,
  76.5, 64.2,
  'KRN Heat Exchanger and Refrigeration Limited is a premier operating enterprise in the HVAC Heat Exchangers sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the HVAC Heat Exchangers industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@krn-heat-exchanger.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@krn-heat-exchanger.com', 'https://www.krn-heat-exchanger.com',
  'https://www.sebi.gov.in/filings/approved-option/krn-heat-exchanger-rhp.html', 'https://ris.kfintech.com/ipostatus', 470.0, 470.0, 113.6,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Garuda Construction & Engineering Limited (garuda-construction)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Garuda Construction & Engineering Limited', 'garuda-construction', 'Mainboard', 'Civil Engineering Construction', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-10-08', '2024-10-08', '2024-10-08', '2024-10-08', '2024-10-15',
  90, 95, 95, 10, 157, 9,
  '264.10', 171.67, 'NSE, BSE',
  46.5, 32.4, 18.8,
  26.5, 35.2, 42.5,
  1, 157, 14915,
  13, 2041, 193895,
  14, 2198, 208810,
  67, 10519, 999305,
  68, 10676, 1014220,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 1109.22,
  76.5, 64.2,
  'Garuda Construction & Engineering Limited is a premier operating enterprise in the Civil Engineering Construction sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Civil Engineering Construction industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@garuda-construction.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@garuda-construction.com', 'https://www.garuda-construction.com',
  'https://www.sebi.gov.in/filings/approved-option/garuda-construction-rhp.html', 'https://ris.kfintech.com/ipostatus', 105.0, 105.0, 10.5,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Hyundai Motor India Limited (hyundai-motor-india)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Hyundai Motor India Limited', 'hyundai-motor-india', 'Mainboard', 'Automobile OEM', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-10-15', '2024-10-15', '2024-10-15', '2024-10-15', '2024-10-22',
  1862, 1960, 1960, 10, 7, 0,
  '27870.16', 18115.6, 'NSE, BSE',
  45.5, 41.4, 17.8,
  29.5, 44.2, 33.5,
  1, 7, 13720,
  14, 98, 192080,
  15, 105, 205800,
  72, 504, 987840,
  73, 511, 1001560,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 117054.67,
  76.5, 64.2,
  'Hyundai Motor India Limited is a premier operating enterprise in the Automobile OEM sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Automobile OEM industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@hyundai-motor-india.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@hyundai-motor-india.com', 'https://www.hyundai-motor-india.com',
  'https://www.sebi.gov.in/filings/approved-option/hyundai-motor-india-rhp.html', 'https://linkintime.co.in/ipostatus', 1934.0, 1934.0, -1.32,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Deepak Builders & Engineers India Limited (deepak-builders-and-engineers)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Deepak Builders & Engineers India Limited', 'deepak-builders-and-engineers', 'Mainboard', 'Infra Contracting', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-10-21', '2024-10-21', '2024-10-21', '2024-10-21', '2024-10-28',
  192, 203, 203, 10, 73, 0,
  '260.04', 169.03, 'NSE, BSE',
  61.5, 32.4, 23.8,
  29.5, 35.2, 27.5,
  1, 73, 14819,
  13, 949, 192647,
  14, 1022, 207466,
  67, 4891, 992873,
  68, 4964, 1007692,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 1092.17,
  76.5, 64.2,
  'Deepak Builders & Engineers India Limited is a premier operating enterprise in the Infra Contracting sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Infra Contracting industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@deepak-builders-and-engineers.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@deepak-builders-and-engineers.com', 'https://www.deepak-builders-and-engineers.com',
  'https://www.sebi.gov.in/filings/approved-option/deepak-builders-and-engineers-rhp.html', 'https://linkintime.co.in/ipostatus', 200.0, 200.0, -1.48,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Waaree Energies Limited (waaree-energies)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Waaree Energies Limited', 'waaree-energies', 'Mainboard', 'Solar Module Manufacturing', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-10-21', '2024-10-21', '2024-10-21', '2024-10-21', '2024-10-28',
  1427, 1503, 1503, 10, 9, 1046,
  '4321.44', 2808.94, 'NSE, BSE',
  47.5, 33.4, 19.8,
  27.5, 36.2, 37.5,
  1, 9, 13527,
  14, 126, 189378,
  15, 135, 202905,
  73, 657, 987471,
  74, 666, 1000998,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 18150.05,
  76.5, 64.2,
  'Waaree Energies Limited is a premier operating enterprise in the Solar Module Manufacturing sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Solar Module Manufacturing industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@waaree-energies.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@waaree-energies.com', 'https://www.waaree-energies.com',
  'https://www.sebi.gov.in/filings/approved-option/waaree-energies-rhp.html', 'https://linkintime.co.in/ipostatus', 2550.0, 2550.0, 69.6,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Godavari Biorefineries Limited (godavari-biorefineries)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Godavari Biorefineries Limited', 'godavari-biorefineries', 'Mainboard', 'Bio-based Chemicals', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-10-23', '2024-10-23', '2024-10-23', '2024-10-23', '2024-10-30',
  334, 352, 352, 10, 42, 0,
  '554.75', 360.59, 'NSE, BSE',
  58.5, 39.4, 20.8,
  30.5, 42.2, 40.5,
  1, 42, 14784,
  13, 546, 192192,
  14, 588, 206976,
  67, 2814, 990528,
  68, 2856, 1005312,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 2329.95,
  76.5, 64.2,
  'Godavari Biorefineries Limited is a premier operating enterprise in the Bio-based Chemicals sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Bio-based Chemicals industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@godavari-biorefineries.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@godavari-biorefineries.com', 'https://www.godavari-biorefineries.com',
  'https://www.sebi.gov.in/filings/approved-option/godavari-biorefineries-rhp.html', 'https://ris.kfintech.com/ipostatus', 308.0, 308.0, -12.5,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Afcons Infrastructure Limited (afcons-infrastructure)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Afcons Infrastructure Limited', 'afcons-infrastructure', 'Mainboard', 'EPC Infrastructure Contracting', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-10-25', '2024-10-25', '2024-10-25', '2024-10-25', '2024-11-04',
  439, 463, 463, 10, 32, 0,
  '5430.00', 3529.5, 'NSE, BSE',
  48.5, 39.4, 20.8,
  24.5, 42.2, 34.5,
  1, 32, 14816,
  13, 416, 192608,
  14, 448, 207424,
  67, 2144, 992672,
  68, 2176, 1007488,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 22806.0,
  76.5, 64.2,
  'Afcons Infrastructure Limited is a premier operating enterprise in the EPC Infrastructure Contracting sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the EPC Infrastructure Contracting industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@afcons-infrastructure.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@afcons-infrastructure.com', 'https://www.afcons-infrastructure.com',
  'https://www.sebi.gov.in/filings/approved-option/afcons-infrastructure-rhp.html', 'https://ris.kfintech.com/ipostatus', 430.0, 430.0, -7.13,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Sagility India Limited (sagility-india)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Sagility India Limited', 'sagility-india', 'Mainboard', 'Healthcare Operations Tech', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-11-05', '2024-11-05', '2024-11-05', '2024-11-05', '2024-11-12',
  28, 30, 30, 10, 500, 1,
  '2106.60', 1369.29, 'NSE, BSE',
  53.5, 39.4, 15.8,
  33.5, 42.2, 31.5,
  1, 500, 15000,
  13, 6500, 195000,
  14, 7000, 210000,
  66, 33000, 990000,
  67, 33500, 1005000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 8847.72,
  76.5, 64.2,
  'Sagility India Limited is a premier operating enterprise in the Healthcare Operations Tech sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Healthcare Operations Tech industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@sagility-india.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@sagility-india.com', 'https://www.sagility-india.com',
  'https://www.sebi.gov.in/filings/approved-option/sagility-india-rhp.html', 'https://linkintime.co.in/ipostatus', 31.05, 31.05, 3.5,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- ACME Solar Holdings Limited (acme-solar-holdings)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'ACME Solar Holdings Limited', 'acme-solar-holdings', 'Mainboard', 'Renewable Energy Power', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-11-06', '2024-11-06', '2024-11-06', '2024-11-06', '2024-11-13',
  274, 289, 289, 10, 51, 0,
  '2900.00', 1885.0, 'NSE, BSE',
  50.5, 31.4, 22.8,
  22.5, 34.2, 38.5,
  1, 51, 14739,
  13, 663, 191607,
  14, 714, 206346,
  67, 3417, 987513,
  68, 3468, 1002252,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 12180.0,
  76.5, 64.2,
  'ACME Solar Holdings Limited is a premier operating enterprise in the Renewable Energy Power sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Renewable Energy Power industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@acme-solar-holdings.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@acme-solar-holdings.com', 'https://www.acme-solar-holdings.com',
  'https://www.sebi.gov.in/filings/approved-option/acme-solar-holdings-rhp.html', 'https://ris.kfintech.com/ipostatus', 259.0, 259.0, -10.3,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Swiggy Limited (swiggy-limited)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Swiggy Limited', 'swiggy-limited', 'Mainboard', 'Food & Quick Commerce Tech', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-11-06', '2024-11-06', '2024-11-06', '2024-11-06', '2024-11-13',
  370, 390, 390, 10, 38, 29,
  '11327.43', 7362.83, 'NSE, BSE',
  59.5, 30.4, 21.8,
  27.5, 33.2, 43.5,
  1, 38, 14820,
  13, 494, 192660,
  14, 532, 207480,
  67, 2546, 992940,
  68, 2584, 1007760,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 47575.21,
  76.5, 64.2,
  'Swiggy Limited is a premier operating enterprise in the Food & Quick Commerce Tech sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Food & Quick Commerce Tech industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@swiggy-limited.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@swiggy-limited.com', 'https://www.swiggy-limited.com',
  'https://www.sebi.gov.in/filings/approved-option/swiggy-limited-rhp.html', 'https://linkintime.co.in/ipostatus', 420.0, 420.0, 7.69,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- NTPC Green Energy Limited (ntpc-green-energy)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'NTPC Green Energy Limited', 'ntpc-green-energy', 'Mainboard', 'Renewable Power Generation', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-11-19', '2024-11-19', '2024-11-19', '2024-11-19', '2024-11-27',
  102, 108, 108, 10, 138, 3,
  '10000.00', 6500.0, 'NSE, BSE',
  49.5, 30.4, 21.8,
  33.5, 33.2, 31.5,
  1, 138, 14904,
  13, 1794, 193752,
  14, 1932, 208656,
  67, 9246, 998568,
  68, 9384, 1013472,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 42000.0,
  76.5, 64.2,
  'NTPC Green Energy Limited is a premier operating enterprise in the Renewable Power Generation sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Renewable Power Generation industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@ntpc-green-energy.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@ntpc-green-energy.com', 'https://www.ntpc-green-energy.com',
  'https://www.sebi.gov.in/filings/approved-option/ntpc-green-energy-rhp.html', 'https://linkintime.co.in/ipostatus', 111.5, 111.5, 3.24,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

