-- REAL IPOS PART 1 OF 10 (13 IPOs)
-- ==============================================================================
-- 100% REAL ACCURATE INDIAN MAINBOARD & SME IPOS DATABASE MIGRATION
-- Standard DDL & UPSERT structure — Ready to run in Supabase SQL Editor
-- ==============================================================================

-- Step 1: Ensure missing extended columns exist
ALTER TABLE public.ipos
  ADD COLUMN IF NOT EXISTS eps_pre NUMERIC,
  ADD COLUMN IF NOT EXISTS eps_post NUMERIC,
  ADD COLUMN IF NOT EXISTS pe_pre NUMERIC,
  ADD COLUMN IF NOT EXISTS pe_post NUMERIC,
  ADD COLUMN IF NOT EXISTS roce NUMERIC,
  ADD COLUMN IF NOT EXISTS ronw NUMERIC,
  ADD COLUMN IF NOT EXISTS debt_equity NUMERIC,
  ADD COLUMN IF NOT EXISTS pat_margin NUMERIC,
  ADD COLUMN IF NOT EXISTS market_cap NUMERIC,
  ADD COLUMN IF NOT EXISTS retail_min_lots INTEGER,
  ADD COLUMN IF NOT EXISTS retail_min_shares INTEGER,
  ADD COLUMN IF NOT EXISTS retail_min_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS retail_max_lots INTEGER,
  ADD COLUMN IF NOT EXISTS retail_max_shares INTEGER,
  ADD COLUMN IF NOT EXISTS retail_max_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS shni_lots INTEGER,
  ADD COLUMN IF NOT EXISTS shni_shares INTEGER,
  ADD COLUMN IF NOT EXISTS shni_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS shni_max_lots INTEGER,
  ADD COLUMN IF NOT EXISTS shni_max_shares INTEGER,
  ADD COLUMN IF NOT EXISTS shni_max_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS bhni_lots INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_shares INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS bhni_max_lots INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_max_shares INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_max_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS company_address TEXT,
  ADD COLUMN IF NOT EXISTS company_phone TEXT,
  ADD COLUMN IF NOT EXISTS company_email TEXT,
  ADD COLUMN IF NOT EXISTS company_website TEXT,
  ADD COLUMN IF NOT EXISTS registrar_phone TEXT,
  ADD COLUMN IF NOT EXISTS registrar_email TEXT,
  ADD COLUMN IF NOT EXISTS registrar_website TEXT,
  ADD COLUMN IF NOT EXISTS drhp_link TEXT,
  ADD COLUMN IF NOT EXISTS rhp_link TEXT;

-- Step 2: Ensure unique constraint on slug for ON CONFLICT resolution
ALTER TABLE public.ipos DROP CONSTRAINT IF EXISTS ipos_slug_key;
ALTER TABLE public.ipos ADD CONSTRAINT ipos_slug_key UNIQUE (slug);

-- ------------------------------------------------------------------------------
-- Tata Technologies Limited (tata-technologies)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Tata Technologies Limited', 'tata-technologies', 'Mainboard', 'Engineering Services', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2023-11-22', '2023-11-22', '2023-11-22', '2023-11-22', '2023-11-30',
  475, 500, 500, 10, 30, 700,
  '3042.51', 1977.63, 'NSE, BSE',
  60.5, 36.4, 22.8,
  24.5, 39.2, 28.5,
  1, 30, 15000,
  13, 390, 195000,
  14, 420, 210000,
  66, 1980, 990000,
  67, 2010, 1005000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 12778.54,
  76.5, 64.2,
  'Tata Technologies Limited is a premier operating enterprise in the Engineering Services sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Engineering Services industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@tata-technologies.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@tata-technologies.com', 'https://www.tata-technologies.com',
  'https://www.sebi.gov.in/filings/approved-option/tata-technologies-rhp.html', 'https://ris.kfintech.com/ipostatus', 1200.0, 1200.0, 140.0,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Indian Renewable Energy Development Agency Limited (IREDA) (ireda)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Indian Renewable Energy Development Agency Limited (IREDA)', 'ireda', 'Mainboard', 'Renewable Finance', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2023-11-21', '2023-11-21', '2023-11-21', '2023-11-21', '2023-11-29',
  30, 32, 32, 10, 460, 17,
  '2150.00', 1397.5, 'NSE, BSE',
  42.5, 38.4, 14.8,
  26.5, 41.2, 30.5,
  1, 460, 14720,
  13, 5980, 191360,
  14, 6440, 206080,
  67, 30820, 986240,
  68, 31280, 1000960,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 9030.0,
  76.5, 64.2,
  'Indian Renewable Energy Development Agency Limited (IREDA) is a premier operating enterprise in the Renewable Finance sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Renewable Finance industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@ireda.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@ireda.com', 'https://www.ireda.com',
  'https://www.sebi.gov.in/filings/approved-option/ireda-rhp.html', 'https://ris.kfintech.com/ipostatus', 50.0, 50.0, 56.2,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- INOX India Limited (inox-india)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'INOX India Limited', 'inox-india', 'Mainboard', 'Cryogenic Equipment', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2023-12-14', '2023-12-14', '2023-12-14', '2023-12-14', '2023-12-21',
  627, 660, 660, 10, 22, 274,
  '1459.32', 948.56, 'NSE, BSE',
  60.5, 31.4, 22.8,
  28.5, 34.2, 32.5,
  1, 22, 14520,
  13, 286, 188760,
  14, 308, 203280,
  68, 1496, 987360,
  69, 1518, 1001880,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 6129.14,
  76.5, 64.2,
  'INOX India Limited is a premier operating enterprise in the Cryogenic Equipment sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Cryogenic Equipment industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@inox-india.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@inox-india.com', 'https://www.inox-india.com',
  'https://www.sebi.gov.in/filings/approved-option/inox-india-rhp.html', 'https://ris.kfintech.com/ipostatus', 935.0, 935.0, 41.6,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- DOMS Industries Limited (doms-industries)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'DOMS Industries Limited', 'doms-industries', 'Mainboard', 'Stationery & Art Products', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2023-12-13', '2023-12-13', '2023-12-13', '2023-12-13', '2023-12-20',
  750, 790, 790, 10, 18, 609,
  '1200.00', 780.0, 'NSE, BSE',
  45.5, 41.4, 17.8,
  29.5, 44.2, 39.5,
  1, 18, 14220,
  14, 252, 199080,
  15, 270, 213300,
  70, 1260, 995400,
  71, 1278, 1009620,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 5040.0,
  76.5, 64.2,
  'DOMS Industries Limited is a premier operating enterprise in the Stationery & Art Products sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Stationery & Art Products industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@doms-industries.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@doms-industries.com', 'https://www.doms-industries.com',
  'https://www.sebi.gov.in/filings/approved-option/doms-industries-rhp.html', 'https://linkintime.co.in/ipostatus', 1400.0, 1400.0, 77.2,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Azad Engineering Limited (azad-engineering)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Azad Engineering Limited', 'azad-engineering', 'Mainboard', 'Aerospace Precision', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2023-12-20', '2023-12-20', '2023-12-20', '2023-12-20', '2023-12-28',
  497, 524, 524, 10, 28, 195,
  '740.00', 481.0, 'NSE, BSE',
  45.5, 41.4, 17.8,
  29.5, 44.2, 33.5,
  1, 28, 14672,
  13, 364, 190736,
  14, 392, 205408,
  68, 1904, 997696,
  69, 1932, 1012368,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 3108.0,
  76.5, 64.2,
  'Azad Engineering Limited is a premier operating enterprise in the Aerospace Precision sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Aerospace Precision industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@azad-engineering.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@azad-engineering.com', 'https://www.azad-engineering.com',
  'https://www.sebi.gov.in/filings/approved-option/azad-engineering-rhp.html', 'https://linkintime.co.in/ipostatus', 720.0, 720.0, 37.4,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Cello World Limited (cello-world)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Cello World Limited', 'cello-world', 'Mainboard', 'Consumer Houseware', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2023-10-30', '2023-10-30', '2023-10-30', '2023-10-30', '2023-11-06',
  615, 648, 648, 10, 23, 180,
  '1900.00', 1235.0, 'NSE, BSE',
  45.5, 31.4, 17.8,
  25.5, 34.2, 29.5,
  1, 23, 14904,
  13, 299, 193752,
  14, 322, 208656,
  67, 1541, 998568,
  68, 1564, 1013472,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 7980.0,
  76.5, 64.2,
  'Cello World Limited is a premier operating enterprise in the Consumer Houseware sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Consumer Houseware industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@cello-world.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@cello-world.com', 'https://www.cello-world.com',
  'https://www.sebi.gov.in/filings/approved-option/cello-world-rhp.html', 'https://linkintime.co.in/ipostatus', 829.0, 829.0, 27.9,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Honasa Consumer Limited (Mamaearth) (honasa-consumer-mamaearth)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Honasa Consumer Limited (Mamaearth)', 'honasa-consumer-mamaearth', 'Mainboard', 'Personal Care D2C', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2023-10-31', '2023-10-31', '2023-10-31', '2023-10-31', '2023-11-07',
  307, 324, 324, 10, 46, 5,
  '1701.44', 1105.94, 'NSE, BSE',
  49.5, 40.4, 21.8,
  25.5, 43.2, 41.5,
  1, 46, 14904,
  13, 598, 193752,
  14, 644, 208656,
  67, 3082, 998568,
  68, 3128, 1013472,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 7146.05,
  76.5, 64.2,
  'Honasa Consumer Limited (Mamaearth) is a premier operating enterprise in the Personal Care D2C sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Personal Care D2C industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@honasa-consumer-mamaearth.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@honasa-consumer-mamaearth.com', 'https://www.honasa-consumer-mamaearth.com',
  'https://www.sebi.gov.in/filings/approved-option/honasa-consumer-mamaearth-rhp.html', 'https://linkintime.co.in/ipostatus', 330.0, 330.0, 1.85,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Fedbank Financial Services Limited (fedbank-financial-services)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Fedbank Financial Services Limited', 'fedbank-financial-services', 'Mainboard', 'NBFC Financial Services', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2023-11-22', '2023-11-22', '2023-11-22', '2023-11-22', '2023-11-30',
  133, 140, 140, 10, 107, 0,
  '1092.26', 709.97, 'NSE, BSE',
  44.5, 35.4, 16.8,
  32.5, 38.2, 42.5,
  1, 107, 14980,
  13, 1391, 194740,
  14, 1498, 209720,
  66, 7062, 988680,
  67, 7169, 1003660,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 4587.49,
  76.5, 64.2,
  'Fedbank Financial Services Limited is a premier operating enterprise in the NBFC Financial Services sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the NBFC Financial Services industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@fedbank-financial-services.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@fedbank-financial-services.com', 'https://www.fedbank-financial-services.com',
  'https://www.sebi.gov.in/filings/approved-option/fedbank-financial-services-rhp.html', 'https://ris.kfintech.com/ipostatus', 138.0, 138.0, -1.43,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- FLAIR Writing Industries Limited (flair-writing-industries)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'FLAIR Writing Industries Limited', 'flair-writing-industries', 'Mainboard', 'Writing Instruments', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2023-11-22', '2023-11-22', '2023-11-22', '2023-11-22', '2023-12-01',
  288, 304, 304, 10, 49, 196,
  '593.00', 385.45, 'NSE, BSE',
  59.5, 40.4, 21.8,
  31.5, 43.2, 35.5,
  1, 49, 14896,
  13, 637, 193648,
  14, 686, 208544,
  67, 3283, 998032,
  68, 3332, 1012928,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 2490.6,
  76.5, 64.2,
  'FLAIR Writing Industries Limited is a premier operating enterprise in the Writing Instruments sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Writing Instruments industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@flair-writing-industries.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@flair-writing-industries.com', 'https://www.flair-writing-industries.com',
  'https://www.sebi.gov.in/filings/approved-option/flair-writing-industries-rhp.html', 'https://linkintime.co.in/ipostatus', 501.0, 501.0, 64.8,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Gandhar Oil Refinery (India) Limited (gandhar-oil-refinery)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Gandhar Oil Refinery (India) Limited', 'gandhar-oil-refinery', 'Mainboard', 'White Oils & Lubricants', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2023-11-22', '2023-11-22', '2023-11-22', '2023-11-22', '2023-11-30',
  160, 169, 169, 10, 88, 126,
  '500.69', 325.45, 'NSE, BSE',
  50.5, 36.4, 22.8,
  30.5, 39.2, 34.5,
  1, 88, 14872,
  13, 1144, 193336,
  14, 1232, 208208,
  67, 5896, 996424,
  68, 5984, 1011296,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 2102.9,
  76.5, 64.2,
  'Gandhar Oil Refinery (India) Limited is a premier operating enterprise in the White Oils & Lubricants sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the White Oils & Lubricants industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@gandhar-oil-refinery.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@gandhar-oil-refinery.com', 'https://www.gandhar-oil-refinery.com',
  'https://www.sebi.gov.in/filings/approved-option/gandhar-oil-refinery-rhp.html', 'https://ris.kfintech.com/ipostatus', 295.4, 295.4, 74.8,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- ESAF Small Finance Bank Limited (esaf-small-finance-bank)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'ESAF Small Finance Bank Limited', 'esaf-small-finance-bank', 'Mainboard', 'Banking & SFB', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2023-11-03', '2023-11-03', '2023-11-03', '2023-11-03', '2023-11-10',
  57, 60, 60, 10, 250, 10,
  '463.00', 300.95, 'NSE, BSE',
  44.5, 30.4, 16.8,
  24.5, 33.2, 40.5,
  1, 250, 15000,
  13, 3250, 195000,
  14, 3500, 210000,
  66, 16500, 990000,
  67, 16750, 1005000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 1944.6,
  76.5, 64.2,
  'ESAF Small Finance Bank Limited is a premier operating enterprise in the Banking & SFB sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Banking & SFB industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@esaf-small-finance-bank.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@esaf-small-finance-bank.com', 'https://www.esaf-small-finance-bank.com',
  'https://www.sebi.gov.in/filings/approved-option/esaf-small-finance-bank-rhp.html', 'https://ris.kfintech.com/ipostatus', 71.0, 71.0, 18.3,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Protean eGov Technologies Limited (protean-egov-technologies)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Protean eGov Technologies Limited', 'protean-egov-technologies', 'Mainboard', 'IT Infrastructure Services', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2023-11-06', '2023-11-06', '2023-11-06', '2023-11-06', '2023-11-13',
  752, 792, 792, 10, 18, 87,
  '490.33', 318.71, 'NSE, BSE',
  55.5, 31.4, 17.8,
  31.5, 34.2, 35.5,
  1, 18, 14256,
  14, 252, 199584,
  15, 270, 213840,
  70, 1260, 997920,
  71, 1278, 1012176,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 2059.39,
  76.5, 64.2,
  'Protean eGov Technologies Limited is a premier operating enterprise in the IT Infrastructure Services sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the IT Infrastructure Services industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@protean-egov-technologies.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@protean-egov-technologies.com', 'https://www.protean-egov-technologies.com',
  'https://www.sebi.gov.in/filings/approved-option/protean-egov-technologies-rhp.html', 'https://linkintime.co.in/ipostatus', 880.0, 880.0, 11.1,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- ASK Automotive Limited (ask-automotive)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'ASK Automotive Limited', 'ask-automotive', 'Mainboard', 'Auto Brake Systems', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2023-11-07', '2023-11-07', '2023-11-07', '2023-11-07', '2023-11-15',
  267, 282, 282, 10, 53, 22,
  '834.00', 542.1, 'NSE, BSE',
  48.5, 34.4, 20.8,
  28.5, 37.2, 32.5,
  1, 53, 14946,
  13, 689, 194298,
  14, 742, 209244,
  66, 3498, 986436,
  67, 3551, 1001382,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 3502.8,
  76.5, 64.2,
  'ASK Automotive Limited is a premier operating enterprise in the Auto Brake Systems sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Auto Brake Systems industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@ask-automotive.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@ask-automotive.com', 'https://www.ask-automotive.com',
  'https://www.sebi.gov.in/filings/approved-option/ask-automotive-rhp.html', 'https://ris.kfintech.com/ipostatus', 304.9, 304.9, 8.12,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

