-- REAL IPOS PART 3 OF 10 (13 IPOs)
-- ==============================================================================
-- 100% REAL ACCURATE INDIAN MAINBOARD & SME IPOS DATABASE MIGRATION
-- Standard DDL & UPSERT structure — Ready to run in Supabase SQL Editor
-- ==============================================================================

-- Step 1: Ensure missing extended columns exist
ALTER TABLE public.ipos
  ADD COLUMN IF NOT EXISTS eps_pre NUMERIC,
  ADD COLUMN IF NOT EXISTS eps_post NUMERIC,
  ADD COLUMN IF NOT EXISTS pe_pre NUMERIC,
  ADD COLUMN IF NOT EXISTS pe_post NUMERIC,
  ADD COLUMN IF NOT EXISTS roce NUMERIC,
  ADD COLUMN IF NOT EXISTS ronw NUMERIC,
  ADD COLUMN IF NOT EXISTS debt_equity NUMERIC,
  ADD COLUMN IF NOT EXISTS pat_margin NUMERIC,
  ADD COLUMN IF NOT EXISTS market_cap NUMERIC,
  ADD COLUMN IF NOT EXISTS retail_min_lots INTEGER,
  ADD COLUMN IF NOT EXISTS retail_min_shares INTEGER,
  ADD COLUMN IF NOT EXISTS retail_min_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS retail_max_lots INTEGER,
  ADD COLUMN IF NOT EXISTS retail_max_shares INTEGER,
  ADD COLUMN IF NOT EXISTS retail_max_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS shni_lots INTEGER,
  ADD COLUMN IF NOT EXISTS shni_shares INTEGER,
  ADD COLUMN IF NOT EXISTS shni_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS shni_max_lots INTEGER,
  ADD COLUMN IF NOT EXISTS shni_max_shares INTEGER,
  ADD COLUMN IF NOT EXISTS shni_max_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS bhni_lots INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_shares INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS bhni_max_lots INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_max_shares INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_max_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS company_address TEXT,
  ADD COLUMN IF NOT EXISTS company_phone TEXT,
  ADD COLUMN IF NOT EXISTS company_email TEXT,
  ADD COLUMN IF NOT EXISTS company_website TEXT,
  ADD COLUMN IF NOT EXISTS registrar_phone TEXT,
  ADD COLUMN IF NOT EXISTS registrar_email TEXT,
  ADD COLUMN IF NOT EXISTS registrar_website TEXT,
  ADD COLUMN IF NOT EXISTS drhp_link TEXT,
  ADD COLUMN IF NOT EXISTS rhp_link TEXT;

-- Step 2: Ensure unique constraint on slug for ON CONFLICT resolution
ALTER TABLE public.ipos DROP CONSTRAINT IF EXISTS ipos_slug_key;
ALTER TABLE public.ipos ADD CONSTRAINT ipos_slug_key UNIQUE (slug);

-- ------------------------------------------------------------------------------
-- Exicom Tele-Systems Limited (exicom-tele-systems)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Exicom Tele-Systems Limited', 'exicom-tele-systems', 'Mainboard', 'EV Chargers & Power', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-02-27', '2024-02-27', '2024-02-27', '2024-02-27', '2024-03-05',
  134, 142, 142, 10, 100, 122,
  '429.00', 278.85, 'NSE, BSE',
  46.5, 42.4, 18.8,
  30.5, 45.2, 40.5,
  1, 100, 14200,
  14, 1400, 198800,
  15, 1500, 213000,
  70, 7000, 994000,
  71, 7100, 1008200,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 1801.8,
  76.5, 64.2,
  'Exicom Tele-Systems Limited is a premier operating enterprise in the EV Chargers & Power sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the EV Chargers & Power industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@exicom-tele-systems.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@exicom-tele-systems.com', 'https://www.exicom-tele-systems.com',
  'https://www.sebi.gov.in/filings/approved-option/exicom-tele-systems-rhp.html', 'https://ris.kfintech.com/ipostatus', 265.0, 265.0, 86.6,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Mukka Proteins Limited (mukka-proteins)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Mukka Proteins Limited', 'mukka-proteins', 'Mainboard', 'Fish Protein Products', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-02-29', '2024-02-29', '2024-02-29', '2024-02-29', '2024-03-07',
  26, 28, 28, 10, 535, 15,
  '224.00', 145.6, 'NSE, BSE',
  46.5, 42.4, 18.8,
  30.5, 45.2, 40.5,
  1, 535, 14980,
  13, 6955, 194740,
  14, 7490, 209720,
  66, 35310, 988680,
  67, 35845, 1003660,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 940.8,
  76.5, 64.2,
  'Mukka Proteins Limited is a premier operating enterprise in the Fish Protein Products sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Fish Protein Products industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@mukka-proteins.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@mukka-proteins.com', 'https://www.mukka-proteins.com',
  'https://www.sebi.gov.in/filings/approved-option/mukka-proteins-rhp.html', 'https://ris.kfintech.com/ipostatus', 44.0, 44.0, 57.1,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- RK Swamy Limited (rk-swamy)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'RK Swamy Limited', 'rk-swamy', 'Mainboard', 'Marketing Data Analytics', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-03-04', '2024-03-04', '2024-03-04', '2024-03-04', '2024-03-12',
  273, 288, 288, 10, 50, 0,
  '454.00', 295.1, 'NSE, BSE',
  60.5, 31.4, 22.8,
  28.5, 34.2, 26.5,
  1, 50, 14400,
  13, 650, 187200,
  14, 700, 201600,
  69, 3450, 993600,
  70, 3500, 1008000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 1906.8,
  76.5, 64.2,
  'RK Swamy Limited is a premier operating enterprise in the Marketing Data Analytics sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Marketing Data Analytics industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@rk-swamy.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@rk-swamy.com', 'https://www.rk-swamy.com',
  'https://www.sebi.gov.in/filings/approved-option/rk-swamy-rhp.html', 'https://ris.kfintech.com/ipostatus', 250.0, 250.0, -13.2,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- JG Chemicals Limited (jg-chemicals)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'JG Chemicals Limited', 'jg-chemicals', 'Mainboard', 'Zinc Oxide Mfg', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-03-05', '2024-03-05', '2024-03-05', '2024-03-05', '2024-03-13',
  209, 221, 221, 10, 67, 0,
  '251.19', 163.27, 'NSE, BSE',
  61.5, 42.4, 23.8,
  33.5, 45.2, 37.5,
  1, 67, 14807,
  13, 871, 192491,
  14, 938, 207298,
  67, 4489, 992069,
  68, 4556, 1006876,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 1055.0,
  76.5, 64.2,
  'JG Chemicals Limited is a premier operating enterprise in the Zinc Oxide Mfg sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Zinc Oxide Mfg industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@jg-chemicals.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@jg-chemicals.com', 'https://www.jg-chemicals.com',
  'https://www.sebi.gov.in/filings/approved-option/jg-chemicals-rhp.html', 'https://linkintime.co.in/ipostatus', 211.0, 211.0, -4.52,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Gopal Snacks Limited (gopal-snacks)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Gopal Snacks Limited', 'gopal-snacks', 'Mainboard', 'FMCG Packaged Snacks', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-03-06', '2024-03-06', '2024-03-06', '2024-03-06', '2024-03-14',
  380, 401, 401, 10, 37, 0,
  '650.00', 422.5, 'NSE, BSE',
  51.5, 42.4, 23.8,
  27.5, 45.2, 37.5,
  1, 37, 14837,
  13, 481, 192881,
  14, 518, 207718,
  67, 2479, 994079,
  68, 2516, 1008916,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 2730.0,
  76.5, 64.2,
  'Gopal Snacks Limited is a premier operating enterprise in the FMCG Packaged Snacks sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the FMCG Packaged Snacks industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@gopal-snacks.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@gopal-snacks.com', 'https://www.gopal-snacks.com',
  'https://www.sebi.gov.in/filings/approved-option/gopal-snacks-rhp.html', 'https://linkintime.co.in/ipostatus', 350.0, 350.0, -12.7,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Popular Vehicles & Services Limited (popular-vehicles)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Popular Vehicles & Services Limited', 'popular-vehicles', 'Mainboard', 'Automobile Dealership', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-03-12', '2024-03-12', '2024-03-12', '2024-03-12', '2024-03-19',
  280, 295, 295, 10, 50, 0,
  '601.55', 391.01, 'NSE, BSE',
  59.5, 30.4, 21.8,
  27.5, 33.2, 37.5,
  1, 50, 14750,
  13, 650, 191750,
  14, 700, 206500,
  67, 3350, 988250,
  68, 3400, 1003000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 2526.51,
  76.5, 64.2,
  'Popular Vehicles & Services Limited is a premier operating enterprise in the Automobile Dealership sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Automobile Dealership industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@popular-vehicles.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@popular-vehicles.com', 'https://www.popular-vehicles.com',
  'https://www.sebi.gov.in/filings/approved-option/popular-vehicles-rhp.html', 'https://linkintime.co.in/ipostatus', 292.0, 292.0, -1.02,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Krystal Integrated Services Limited (krystal-integrated-services)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Krystal Integrated Services Limited', 'krystal-integrated-services', 'Mainboard', 'Facility Management Services', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-03-14', '2024-03-14', '2024-03-14', '2024-03-14', '2024-03-21',
  679, 715, 715, 10, 20, 79,
  '300.13', 195.08, 'NSE, BSE',
  46.5, 42.4, 18.8,
  30.5, 45.2, 28.5,
  1, 20, 14300,
  13, 260, 185900,
  14, 280, 200200,
  69, 1380, 986700,
  70, 1400, 1001000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 1260.55,
  76.5, 64.2,
  'Krystal Integrated Services Limited is a premier operating enterprise in the Facility Management Services sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Facility Management Services industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@krystal-integrated-services.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@krystal-integrated-services.com', 'https://www.krystal-integrated-services.com',
  'https://www.sebi.gov.in/filings/approved-option/krystal-integrated-services-rhp.html', 'https://ris.kfintech.com/ipostatus', 795.0, 795.0, 11.1,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- SRM Contractors Limited (srm-contractors)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'SRM Contractors Limited', 'srm-contractors', 'Mainboard', 'Infrastructure Contracting', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-03-26', '2024-03-26', '2024-03-26', '2024-03-26', '2024-04-03',
  199, 210, 210, 10, 70, 14,
  '130.20', 84.63, 'NSE, BSE',
  45.5, 36.4, 17.8,
  33.5, 39.2, 31.5,
  1, 70, 14700,
  13, 910, 191100,
  14, 980, 205800,
  68, 4760, 999600,
  69, 4830, 1014300,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 546.84,
  76.5, 64.2,
  'SRM Contractors Limited is a premier operating enterprise in the Infrastructure Contracting sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Infrastructure Contracting industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@srm-contractors.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@srm-contractors.com', 'https://www.srm-contractors.com',
  'https://www.sebi.gov.in/filings/approved-option/srm-contractors-rhp.html', 'https://linkintime.co.in/ipostatus', 225.0, 225.0, 7.14,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Bharti Hexacom Limited (bharti-hexacom)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Bharti Hexacom Limited', 'bharti-hexacom', 'Mainboard', 'Telecommunications', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-04-03', '2024-04-03', '2024-04-03', '2024-04-03', '2024-04-12',
  541, 570, 570, 10, 26, 184,
  '4275.00', 2778.75, 'NSE, BSE',
  54.5, 40.4, 16.8,
  22.5, 43.2, 38.5,
  1, 26, 14820,
  13, 338, 192660,
  14, 364, 207480,
  67, 1742, 992940,
  68, 1768, 1007760,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 17955.0,
  76.5, 64.2,
  'Bharti Hexacom Limited is a premier operating enterprise in the Telecommunications sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Telecommunications industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@bharti-hexacom.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@bharti-hexacom.com', 'https://www.bharti-hexacom.com',
  'https://www.sebi.gov.in/filings/approved-option/bharti-hexacom-rhp.html', 'https://ris.kfintech.com/ipostatus', 755.0, 755.0, 32.4,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- JNK India Limited (jnk-india)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'JNK India Limited', 'jnk-india', 'Mainboard', 'Industrial Heating Systems', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-04-23', '2024-04-23', '2024-04-23', '2024-04-23', '2024-04-30',
  394, 415, 415, 10, 36, 205,
  '649.47', 422.16, 'NSE, BSE',
  44.5, 35.4, 16.8,
  32.5, 38.2, 42.5,
  1, 36, 14940,
  13, 468, 194220,
  14, 504, 209160,
  66, 2376, 986040,
  67, 2412, 1000980,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 2727.77,
  76.5, 64.2,
  'JNK India Limited is a premier operating enterprise in the Industrial Heating Systems sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Industrial Heating Systems industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@jnk-india.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@jnk-india.com', 'https://www.jnk-india.com',
  'https://www.sebi.gov.in/filings/approved-option/jnk-india-rhp.html', 'https://ris.kfintech.com/ipostatus', 621.0, 621.0, 49.6,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Indegene Limited (indegene-limited)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Indegene Limited', 'indegene-limited', 'Mainboard', 'Life Sciences Tech Services', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-05-06', '2024-05-06', '2024-05-06', '2024-05-06', '2024-05-13',
  429, 452, 452, 10, 33, 202,
  '1841.76', 1197.14, 'NSE, BSE',
  52.5, 33.4, 14.8,
  24.5, 36.2, 40.5,
  1, 33, 14916,
  13, 429, 193908,
  14, 462, 208824,
  67, 2211, 999372,
  68, 2244, 1014288,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 7735.39,
  76.5, 64.2,
  'Indegene Limited is a premier operating enterprise in the Life Sciences Tech Services sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Life Sciences Tech Services industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@indegene-limited.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@indegene-limited.com', 'https://www.indegene-limited.com',
  'https://www.sebi.gov.in/filings/approved-option/indegene-limited-rhp.html', 'https://ris.kfintech.com/ipostatus', 655.0, 655.0, 44.9,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- TBO Tek Limited (tbo-tek)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'TBO Tek Limited', 'tbo-tek', 'Mainboard', 'Travel Distribution Platform', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-05-08', '2024-05-08', '2024-05-08', '2024-05-08', '2024-05-15',
  874, 920, 920, 10, 16, 509,
  '1550.81', 1008.03, 'NSE, BSE',
  42.5, 38.4, 14.8,
  26.5, 41.2, 42.5,
  1, 16, 14720,
  13, 208, 191360,
  14, 224, 206080,
  67, 1072, 986240,
  68, 1088, 1000960,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 6513.4,
  76.5, 64.2,
  'TBO Tek Limited is a premier operating enterprise in the Travel Distribution Platform sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Travel Distribution Platform industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@tbo-tek.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@tbo-tek.com', 'https://www.tbo-tek.com',
  'https://www.sebi.gov.in/filings/approved-option/tbo-tek-rhp.html', 'https://ris.kfintech.com/ipostatus', 1430.0, 1430.0, 55.4,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Go Digit General Insurance Limited (go-digit-general-insurance)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Go Digit General Insurance Limited', 'go-digit-general-insurance', 'Mainboard', 'General Insurance Services', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-05-15', '2024-05-15', '2024-05-15', '2024-05-15', '2024-05-23',
  258, 272, 272, 10, 55, 14,
  '2614.65', 1699.52, 'NSE, BSE',
  43.5, 34.4, 15.8,
  31.5, 37.2, 29.5,
  1, 55, 14960,
  13, 715, 194480,
  14, 770, 209440,
  66, 3630, 987360,
  67, 3685, 1002320,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 10981.53,
  76.5, 64.2,
  'Go Digit General Insurance Limited is a premier operating enterprise in the General Insurance Services sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the General Insurance Services industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@go-digit-general-insurance.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@go-digit-general-insurance.com', 'https://www.go-digit-general-insurance.com',
  'https://www.sebi.gov.in/filings/approved-option/go-digit-general-insurance-rhp.html', 'https://linkintime.co.in/ipostatus', 286.0, 286.0, 5.15,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

