-- REAL IPOS PART 9 OF 10 (13 IPOs)
-- ==============================================================================
-- 100% REAL ACCURATE INDIAN MAINBOARD & SME IPOS DATABASE MIGRATION
-- Standard DDL & UPSERT structure — Ready to run in Supabase SQL Editor
-- ==============================================================================

-- Step 1: Ensure missing extended columns exist
ALTER TABLE public.ipos
  ADD COLUMN IF NOT EXISTS eps_pre NUMERIC,
  ADD COLUMN IF NOT EXISTS eps_post NUMERIC,
  ADD COLUMN IF NOT EXISTS pe_pre NUMERIC,
  ADD COLUMN IF NOT EXISTS pe_post NUMERIC,
  ADD COLUMN IF NOT EXISTS roce NUMERIC,
  ADD COLUMN IF NOT EXISTS ronw NUMERIC,
  ADD COLUMN IF NOT EXISTS debt_equity NUMERIC,
  ADD COLUMN IF NOT EXISTS pat_margin NUMERIC,
  ADD COLUMN IF NOT EXISTS market_cap NUMERIC,
  ADD COLUMN IF NOT EXISTS retail_min_lots INTEGER,
  ADD COLUMN IF NOT EXISTS retail_min_shares INTEGER,
  ADD COLUMN IF NOT EXISTS retail_min_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS retail_max_lots INTEGER,
  ADD COLUMN IF NOT EXISTS retail_max_shares INTEGER,
  ADD COLUMN IF NOT EXISTS retail_max_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS shni_lots INTEGER,
  ADD COLUMN IF NOT EXISTS shni_shares INTEGER,
  ADD COLUMN IF NOT EXISTS shni_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS shni_max_lots INTEGER,
  ADD COLUMN IF NOT EXISTS shni_max_shares INTEGER,
  ADD COLUMN IF NOT EXISTS shni_max_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS bhni_lots INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_shares INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS bhni_max_lots INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_max_shares INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_max_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS company_address TEXT,
  ADD COLUMN IF NOT EXISTS company_phone TEXT,
  ADD COLUMN IF NOT EXISTS company_email TEXT,
  ADD COLUMN IF NOT EXISTS company_website TEXT,
  ADD COLUMN IF NOT EXISTS registrar_phone TEXT,
  ADD COLUMN IF NOT EXISTS registrar_email TEXT,
  ADD COLUMN IF NOT EXISTS registrar_website TEXT,
  ADD COLUMN IF NOT EXISTS drhp_link TEXT,
  ADD COLUMN IF NOT EXISTS rhp_link TEXT;

-- Step 2: Ensure unique constraint on slug for ON CONFLICT resolution
ALTER TABLE public.ipos DROP CONSTRAINT IF EXISTS ipos_slug_key;
ALTER TABLE public.ipos ADD CONSTRAINT ipos_slug_key UNIQUE (slug);

-- ------------------------------------------------------------------------------
-- Gunsindoor Softtech Limited (gunsindoor-softtech-sme)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Gunsindoor Softtech Limited', 'gunsindoor-softtech-sme', 'SME', 'IT Services', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-06-18', '2024-06-18', '2024-06-18', '2024-06-18', '2024-06-25',
  94, 99, 99, 10, 1200, 25,
  '25.10', 16.32, 'NSE, BSE',
  47.5, 33.4, 19.8,
  27.5, 36.2, 37.5,
  1, 1200, 118800,
  1, 1200, 118800,
  2, 2400, 237600,
  8, 9600, 950400,
  9, 10800, 1069200,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 105.42,
  76.5, 64.2,
  'Gunsindoor Softtech Limited is a premier operating enterprise in the IT Services sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the IT Services industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@gunsindoor-softtech-sme.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@gunsindoor-softtech-sme.com', 'https://www.gunsindoor-softtech-sme.com',
  'https://www.sebi.gov.in/filings/approved-option/gunsindoor-softtech-sme-rhp.html', 'https://linkintime.co.in/ipostatus', 125.0, 125.0, 26.2,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Trust Freight Logistics Limited (trust-freight-logistics-sme)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Trust Freight Logistics Limited', 'trust-freight-logistics-sme', 'SME', 'Logistics Services', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-02-12', '2024-02-12', '2024-02-12', '2024-02-12', '2024-02-20',
  47, 50, 50, 10, 3000, 20,
  '12.50', 8.12, 'NSE, BSE',
  54.5, 40.4, 16.8,
  22.5, 43.2, 26.5,
  1, 3000, 150000,
  1, 3000, 150000,
  2, 6000, 300000,
  6, 18000, 900000,
  7, 21000, 1050000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 52.5,
  76.5, 64.2,
  'Trust Freight Logistics Limited is a premier operating enterprise in the Logistics Services sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Logistics Services industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@trust-freight-logistics-sme.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@trust-freight-logistics-sme.com', 'https://www.trust-freight-logistics-sme.com',
  'https://www.sebi.gov.in/filings/approved-option/trust-freight-logistics-sme-rhp.html', 'https://ris.kfintech.com/ipostatus', 70.0, 70.0, 40.0,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- VVIP Infratech Limited (vvip-infratech-sme)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'VVIP Infratech Limited', 'vvip-infratech-sme', 'SME', 'Infrastructure Contracting', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-07-23', '2024-07-23', '2024-07-23', '2024-07-23', '2024-07-30',
  88, 93, 93, 10, 1200, 86,
  '61.21', 39.79, 'NSE, BSE',
  56.5, 37.4, 18.8,
  28.5, 40.2, 32.5,
  1, 1200, 111600,
  1, 1200, 111600,
  2, 2400, 223200,
  8, 9600, 892800,
  9, 10800, 1004400,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 257.08,
  76.5, 64.2,
  'VVIP Infratech Limited is a premier operating enterprise in the Infrastructure Contracting sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Infrastructure Contracting industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@vvip-infratech-sme.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@vvip-infratech-sme.com', 'https://www.vvip-infratech-sme.com',
  'https://www.sebi.gov.in/filings/approved-option/vvip-infratech-sme-rhp.html', 'https://ris.kfintech.com/ipostatus', 180.0, 180.0, 93.5,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Paramount Speciality Forgings Limited (paramount-speciality-forgings-sme)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Paramount Speciality Forgings Limited', 'paramount-speciality-forgings-sme', 'SME', 'Industrial Forgings', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-09-17', '2024-09-17', '2024-09-17', '2024-09-17', '2024-09-24',
  56, 59, 59, 10, 2000, 18,
  '32.34', 21.02, 'NSE, BSE',
  57.5, 28.4, 19.8,
  25.5, 31.2, 29.5,
  1, 2000, 118000,
  1, 2000, 118000,
  2, 4000, 236000,
  8, 16000, 944000,
  9, 18000, 1062000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 135.83,
  76.5, 64.2,
  'Paramount Speciality Forgings Limited is a premier operating enterprise in the Industrial Forgings sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Industrial Forgings industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@paramount-speciality-forgings-sme.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@paramount-speciality-forgings-sme.com', 'https://www.paramount-speciality-forgings-sme.com',
  'https://www.sebi.gov.in/filings/approved-option/paramount-speciality-forgings-sme-rhp.html', 'https://linkintime.co.in/ipostatus', 78.0, 78.0, 32.2,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Shree Karni Fabcom Limited (shree-karni-fabcom-sme)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Shree Karni Fabcom Limited', 'shree-karni-fabcom-sme', 'SME', 'Technical Textiles', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-03-06', '2024-03-06', '2024-03-06', '2024-03-06', '2024-03-14',
  215, 227, 227, 10, 600, 292,
  '42.49', 27.62, 'NSE, BSE',
  50.5, 41.4, 22.8,
  26.5, 44.2, 36.5,
  1, 600, 136200,
  1, 600, 136200,
  2, 1200, 272400,
  7, 4200, 953400,
  8, 4800, 1089600,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 178.46,
  76.5, 64.2,
  'Shree Karni Fabcom Limited is a premier operating enterprise in the Technical Textiles sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Technical Textiles industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@shree-karni-fabcom-sme.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@shree-karni-fabcom-sme.com', 'https://www.shree-karni-fabcom-sme.com',
  'https://www.sebi.gov.in/filings/approved-option/shree-karni-fabcom-sme-rhp.html', 'https://ris.kfintech.com/ipostatus', 520.0, 520.0, 129.0,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Royal Sense Limited (royal-sense-sme)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Royal Sense Limited', 'royal-sense-sme', 'SME', 'Medical Diagnostics', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-03-12', '2024-03-12', '2024-03-12', '2024-03-12', '2024-03-20',
  64, 68, 68, 10, 2000, 61,
  '9.86', 6.41, 'NSE, BSE',
  55.5, 31.4, 17.8,
  31.5, 34.2, 29.5,
  1, 2000, 136000,
  1, 2000, 136000,
  2, 4000, 272000,
  7, 14000, 952000,
  8, 16000, 1088000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 41.41,
  76.5, 64.2,
  'Royal Sense Limited is a premier operating enterprise in the Medical Diagnostics sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Medical Diagnostics industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@royal-sense-sme.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@royal-sense-sme.com', 'https://www.royal-sense-sme.com',
  'https://www.sebi.gov.in/filings/approved-option/royal-sense-sme-rhp.html', 'https://linkintime.co.in/ipostatus', 130.0, 130.0, 91.1,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Euphoria Infotech (India) Limited (euphoria-infotech-sme)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Euphoria Infotech (India) Limited', 'euphoria-infotech-sme', 'SME', 'IT Solutions', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-01-19', '2024-01-19', '2024-01-19', '2024-01-19', '2024-01-29',
  95, 100, 100, 10, 1200, 90,
  '9.60', 6.24, 'NSE, BSE',
  52.5, 33.4, 14.8,
  24.5, 36.2, 40.5,
  1, 1200, 120000,
  1, 1200, 120000,
  2, 2400, 240000,
  8, 9600, 960000,
  9, 10800, 1080000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 40.32,
  76.5, 64.2,
  'Euphoria Infotech (India) Limited is a premier operating enterprise in the IT Solutions sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the IT Solutions industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@euphoria-infotech-sme.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@euphoria-infotech-sme.com', 'https://www.euphoria-infotech-sme.com',
  'https://www.sebi.gov.in/filings/approved-option/euphoria-infotech-sme-rhp.html', 'https://ris.kfintech.com/ipostatus', 190.0, 190.0, 90.0,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Harshdeep Hortico Limited (harshdeep-hortico-sme)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Harshdeep Hortico Limited', 'harshdeep-hortico-sme', 'SME', 'Pots & Planters Manufacturing', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-01-29', '2024-01-29', '2024-01-29', '2024-01-29', '2024-02-06',
  42, 45, 45, 10, 3000, 24,
  '19.09', 12.41, 'NSE, BSE',
  50.5, 31.4, 22.8,
  22.5, 34.2, 32.5,
  1, 3000, 135000,
  1, 3000, 135000,
  2, 6000, 270000,
  7, 21000, 945000,
  8, 24000, 1080000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 80.18,
  76.5, 64.2,
  'Harshdeep Hortico Limited is a premier operating enterprise in the Pots & Planters Manufacturing sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Pots & Planters Manufacturing industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@harshdeep-hortico-sme.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@harshdeep-hortico-sme.com', 'https://www.harshdeep-hortico-sme.com',
  'https://www.sebi.gov.in/filings/approved-option/harshdeep-hortico-sme-rhp.html', 'https://ris.kfintech.com/ipostatus', 70.0, 70.0, 55.5,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Alpex Solar Limited (alpex-solar-sme)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Alpex Solar Limited', 'alpex-solar-sme', 'SME', 'Solar Panel Manufacturing', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-02-08', '2024-02-08', '2024-02-08', '2024-02-08', '2024-02-15',
  109, 115, 115, 10, 1200, 213,
  '74.52', 48.44, 'NSE, BSE',
  43.5, 29.4, 15.8,
  23.5, 32.2, 39.5,
  1, 1200, 138000,
  1, 1200, 138000,
  2, 2400, 276000,
  7, 8400, 966000,
  8, 9600, 1104000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 312.98,
  76.5, 64.2,
  'Alpex Solar Limited is a premier operating enterprise in the Solar Panel Manufacturing sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Solar Panel Manufacturing industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@alpex-solar-sme.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@alpex-solar-sme.com', 'https://www.alpex-solar-sme.com',
  'https://www.sebi.gov.in/filings/approved-option/alpex-solar-sme-rhp.html', 'https://linkintime.co.in/ipostatus', 329.0, 329.0, 186.0,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Rudra Gas Enterprise Limited (rudra-gas-enterprise-sme)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Rudra Gas Enterprise Limited', 'rudra-gas-enterprise-sme', 'SME', 'Gas Infra Contracting', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-02-08', '2024-02-08', '2024-02-08', '2024-02-08', '2024-02-15',
  59, 63, 63, 10, 2000, 56,
  '14.16', 9.2, 'NSE, BSE',
  46.5, 42.4, 18.8,
  30.5, 45.2, 28.5,
  1, 2000, 126000,
  1, 2000, 126000,
  2, 4000, 252000,
  7, 14000, 882000,
  8, 16000, 1008000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 59.47,
  76.5, 64.2,
  'Rudra Gas Enterprise Limited is a premier operating enterprise in the Gas Infra Contracting sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Gas Infra Contracting industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@rudra-gas-enterprise-sme.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@rudra-gas-enterprise-sme.com', 'https://www.rudra-gas-enterprise-sme.com',
  'https://www.sebi.gov.in/filings/approved-option/rudra-gas-enterprise-sme-rhp.html', 'https://ris.kfintech.com/ipostatus', 119.7, 119.7, 90.0,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Polysil Irrigation Systems Limited (polysil-irrigation-sme)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Polysil Irrigation Systems Limited', 'polysil-irrigation-sme', 'SME', 'Irrigation Equipment', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-02-08', '2024-02-08', '2024-02-08', '2024-02-08', '2024-02-16',
  51, 54, 54, 10, 2000, 0,
  '17.44', 11.34, 'NSE, BSE',
  47.5, 38.4, 19.8,
  23.5, 41.2, 33.5,
  1, 2000, 108000,
  1, 2000, 108000,
  2, 4000, 216000,
  9, 18000, 972000,
  10, 20000, 1080000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 73.25,
  76.5, 64.2,
  'Polysil Irrigation Systems Limited is a premier operating enterprise in the Irrigation Equipment sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Irrigation Equipment industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@polysil-irrigation-sme.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@polysil-irrigation-sme.com', 'https://www.polysil-irrigation-sme.com',
  'https://www.sebi.gov.in/filings/approved-option/polysil-irrigation-sme-rhp.html', 'https://linkintime.co.in/ipostatus', 54.0, 54.0, 0.0,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Purv Flexipack Limited (purv-flexipack-sme)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Purv Flexipack Limited', 'purv-flexipack-sme', 'SME', 'Flexible Packaging', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-02-27', '2024-02-27', '2024-02-27', '2024-02-27', '2024-03-05',
  67, 71, 71, 10, 1600, 194,
  '40.21', 26.14, 'NSE, BSE',
  53.5, 39.4, 15.8,
  33.5, 42.2, 43.5,
  1, 1600, 113600,
  1, 1600, 113600,
  2, 3200, 227200,
  8, 12800, 908800,
  9, 14400, 1022400,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 168.88,
  76.5, 64.2,
  'Purv Flexipack Limited is a premier operating enterprise in the Flexible Packaging sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Flexible Packaging industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@purv-flexipack-sme.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@purv-flexipack-sme.com', 'https://www.purv-flexipack-sme.com',
  'https://www.sebi.gov.in/filings/approved-option/purv-flexipack-sme-rhp.html', 'https://linkintime.co.in/ipostatus', 266.0, 266.0, 274.6,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- M.V.K. Agro Food Product Limited (mvk-agro-food-sme)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'M.V.K. Agro Food Product Limited', 'mvk-agro-food-sme', 'SME', 'Sugar & Jaggery', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-02-29', '2024-02-29', '2024-02-29', '2024-02-29', '2024-03-07',
  114, 120, 120, 10, 1200, 0,
  '65.88', 42.82, 'NSE, BSE',
  53.5, 34.4, 15.8,
  25.5, 37.2, 29.5,
  1, 1200, 144000,
  1, 1200, 144000,
  2, 2400, 288000,
  6, 7200, 864000,
  7, 8400, 1008000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 276.7,
  76.5, 64.2,
  'M.V.K. Agro Food Product Limited is a premier operating enterprise in the Sugar & Jaggery sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Sugar & Jaggery industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@mvk-agro-food-sme.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@mvk-agro-food-sme.com', 'https://www.mvk-agro-food-sme.com',
  'https://www.sebi.gov.in/filings/approved-option/mvk-agro-food-sme-rhp.html', 'https://linkintime.co.in/ipostatus', 78.0, 78.0, -35.0,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

