-- REAL IPOS PART 4 OF 10 (13 IPOs)
-- ==============================================================================
-- 100% REAL ACCURATE INDIAN MAINBOARD & SME IPOS DATABASE MIGRATION
-- Standard DDL & UPSERT structure — Ready to run in Supabase SQL Editor
-- ==============================================================================

-- Step 1: Ensure missing extended columns exist
ALTER TABLE public.ipos
  ADD COLUMN IF NOT EXISTS eps_pre NUMERIC,
  ADD COLUMN IF NOT EXISTS eps_post NUMERIC,
  ADD COLUMN IF NOT EXISTS pe_pre NUMERIC,
  ADD COLUMN IF NOT EXISTS pe_post NUMERIC,
  ADD COLUMN IF NOT EXISTS roce NUMERIC,
  ADD COLUMN IF NOT EXISTS ronw NUMERIC,
  ADD COLUMN IF NOT EXISTS debt_equity NUMERIC,
  ADD COLUMN IF NOT EXISTS pat_margin NUMERIC,
  ADD COLUMN IF NOT EXISTS market_cap NUMERIC,
  ADD COLUMN IF NOT EXISTS retail_min_lots INTEGER,
  ADD COLUMN IF NOT EXISTS retail_min_shares INTEGER,
  ADD COLUMN IF NOT EXISTS retail_min_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS retail_max_lots INTEGER,
  ADD COLUMN IF NOT EXISTS retail_max_shares INTEGER,
  ADD COLUMN IF NOT EXISTS retail_max_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS shni_lots INTEGER,
  ADD COLUMN IF NOT EXISTS shni_shares INTEGER,
  ADD COLUMN IF NOT EXISTS shni_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS shni_max_lots INTEGER,
  ADD COLUMN IF NOT EXISTS shni_max_shares INTEGER,
  ADD COLUMN IF NOT EXISTS shni_max_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS bhni_lots INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_shares INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS bhni_max_lots INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_max_shares INTEGER,
  ADD COLUMN IF NOT EXISTS bhni_max_amount NUMERIC,
  ADD COLUMN IF NOT EXISTS company_address TEXT,
  ADD COLUMN IF NOT EXISTS company_phone TEXT,
  ADD COLUMN IF NOT EXISTS company_email TEXT,
  ADD COLUMN IF NOT EXISTS company_website TEXT,
  ADD COLUMN IF NOT EXISTS registrar_phone TEXT,
  ADD COLUMN IF NOT EXISTS registrar_email TEXT,
  ADD COLUMN IF NOT EXISTS registrar_website TEXT,
  ADD COLUMN IF NOT EXISTS drhp_link TEXT,
  ADD COLUMN IF NOT EXISTS rhp_link TEXT;

-- Step 2: Ensure unique constraint on slug for ON CONFLICT resolution
ALTER TABLE public.ipos DROP CONSTRAINT IF EXISTS ipos_slug_key;
ALTER TABLE public.ipos ADD CONSTRAINT ipos_slug_key UNIQUE (slug);

-- ------------------------------------------------------------------------------
-- Awfis Space Solutions Limited (awfis-space-solutions)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Awfis Space Solutions Limited', 'awfis-space-solutions', 'Mainboard', 'Flexible Workspaces', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-05-22', '2024-05-22', '2024-05-22', '2024-05-22', '2024-05-30',
  363, 383, 383, 10, 39, 51,
  '598.93', 389.3, 'NSE, BSE',
  56.5, 37.4, 18.8,
  28.5, 40.2, 26.5,
  1, 39, 14937,
  13, 507, 194181,
  14, 546, 209118,
  66, 2574, 985842,
  67, 2613, 1000779,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 2515.51,
  76.5, 64.2,
  'Awfis Space Solutions Limited is a premier operating enterprise in the Flexible Workspaces sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Flexible Workspaces industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@awfis-space-solutions.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@awfis-space-solutions.com', 'https://www.awfis-space-solutions.com',
  'https://www.sebi.gov.in/filings/approved-option/awfis-space-solutions-rhp.html', 'https://ris.kfintech.com/ipostatus', 435.0, 435.0, 13.5,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Kronox Lab Sciences Limited (kronox-lab-sciences)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Kronox Lab Sciences Limited', 'kronox-lab-sciences', 'Mainboard', 'Specialty Fine Chemicals', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-06-03', '2024-06-03', '2024-06-03', '2024-06-03', '2024-06-10',
  131, 138, 138, 10, 100, 26,
  '130.15', 84.6, 'NSE, BSE',
  55.5, 41.4, 17.8,
  23.5, 44.2, 33.5,
  1, 100, 13800,
  14, 1400, 193200,
  15, 1500, 207000,
  72, 7200, 993600,
  73, 7300, 1007400,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 546.63,
  76.5, 64.2,
  'Kronox Lab Sciences Limited is a premier operating enterprise in the Specialty Fine Chemicals sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Specialty Fine Chemicals industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@kronox-lab-sciences.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@kronox-lab-sciences.com', 'https://www.kronox-lab-sciences.com',
  'https://www.sebi.gov.in/filings/approved-option/kronox-lab-sciences-rhp.html', 'https://linkintime.co.in/ipostatus', 165.0, 165.0, 19.5,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Le Travenues Technology Limited (Ixigo) (le-travenues-technology-ixigo)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Le Travenues Technology Limited (Ixigo)', 'le-travenues-technology-ixigo', 'Mainboard', 'Travel OTA Tech Platform', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-06-10', '2024-06-10', '2024-06-10', '2024-06-10', '2024-06-18',
  88, 93, 93, 10, 161, 45,
  '740.10', 481.07, 'NSE, BSE',
  58.5, 34.4, 20.8,
  22.5, 37.2, 32.5,
  1, 161, 14973,
  13, 2093, 194649,
  14, 2254, 209622,
  66, 10626, 988218,
  67, 10787, 1003191,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 3108.42,
  76.5, 64.2,
  'Le Travenues Technology Limited (Ixigo) is a premier operating enterprise in the Travel OTA Tech Platform sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Travel OTA Tech Platform industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@le-travenues-technology-ixigo.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@le-travenues-technology-ixigo.com', 'https://www.le-travenues-technology-ixigo.com',
  'https://www.sebi.gov.in/filings/approved-option/le-travenues-technology-ixigo-rhp.html', 'https://ris.kfintech.com/ipostatus', 138.1, 138.1, 48.5,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- DEE Development Engineers Limited (dee-development-engineers)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'DEE Development Engineers Limited', 'dee-development-engineers', 'Mainboard', 'Process Piping Solutions', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-06-19', '2024-06-19', '2024-06-19', '2024-06-19', '2024-06-26',
  192, 203, 203, 10, 73, 122,
  '418.01', 271.71, 'NSE, BSE',
  49.5, 30.4, 21.8,
  33.5, 33.2, 43.5,
  1, 73, 14819,
  13, 949, 192647,
  14, 1022, 207466,
  67, 4891, 992873,
  68, 4964, 1007692,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 1755.64,
  76.5, 64.2,
  'DEE Development Engineers Limited is a premier operating enterprise in the Process Piping Solutions sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Process Piping Solutions industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@dee-development-engineers.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@dee-development-engineers.com', 'https://www.dee-development-engineers.com',
  'https://www.sebi.gov.in/filings/approved-option/dee-development-engineers-rhp.html', 'https://linkintime.co.in/ipostatus', 325.0, 325.0, 60.1,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Akme Fintrade (India) Limited (akme-fintrade)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Akme Fintrade (India) Limited', 'akme-fintrade', 'Mainboard', 'NBFC Financial Services', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-06-19', '2024-06-19', '2024-06-19', '2024-06-19', '2024-06-26',
  114, 120, 120, 10, 125, 6,
  '132.00', 85.8, 'NSE, BSE',
  46.5, 37.4, 18.8,
  22.5, 40.2, 32.5,
  1, 125, 15000,
  13, 1625, 195000,
  14, 1750, 210000,
  66, 8250, 990000,
  67, 8375, 1005000,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 554.4,
  76.5, 64.2,
  'Akme Fintrade (India) Limited is a premier operating enterprise in the NBFC Financial Services sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the NBFC Financial Services industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@akme-fintrade.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@akme-fintrade.com', 'https://www.akme-fintrade.com',
  'https://www.sebi.gov.in/filings/approved-option/akme-fintrade-rhp.html', 'https://ris.kfintech.com/ipostatus', 127.0, 127.0, 5.83,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Stanley Lifestyles Limited (stanley-lifestyles)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Stanley Lifestyles Limited', 'stanley-lifestyles', 'Mainboard', 'Luxury Furniture Mfg', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-06-21', '2024-06-21', '2024-06-21', '2024-06-21', '2024-06-28',
  350, 369, 369, 10, 40, 129,
  '537.02', 349.06, 'NSE, BSE',
  46.5, 37.4, 18.8,
  22.5, 40.2, 26.5,
  1, 40, 14760,
  13, 520, 191880,
  14, 560, 206640,
  67, 2680, 988920,
  68, 2720, 1003680,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 2255.48,
  76.5, 64.2,
  'Stanley Lifestyles Limited is a premier operating enterprise in the Luxury Furniture Mfg sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Luxury Furniture Mfg industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@stanley-lifestyles.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@stanley-lifestyles.com', 'https://www.stanley-lifestyles.com',
  'https://www.sebi.gov.in/filings/approved-option/stanley-lifestyles-rhp.html', 'https://ris.kfintech.com/ipostatus', 499.0, 499.0, 35.2,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Vraj Iron & Steel Limited (vraj-iron-and-steel)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Vraj Iron & Steel Limited', 'vraj-iron-and-steel', 'Mainboard', 'Sponge Iron & Steel', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-06-26', '2024-06-26', '2024-06-26', '2024-06-26', '2024-07-03',
  196, 207, 207, 10, 72, 32,
  '171.00', 111.15, 'NSE, BSE',
  57.5, 38.4, 19.8,
  29.5, 41.2, 33.5,
  1, 72, 14904,
  13, 936, 193752,
  14, 1008, 208656,
  67, 4824, 998568,
  68, 4896, 1013472,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 718.2,
  76.5, 64.2,
  'Vraj Iron & Steel Limited is a premier operating enterprise in the Sponge Iron & Steel sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Sponge Iron & Steel industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@vraj-iron-and-steel.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@vraj-iron-and-steel.com', 'https://www.vraj-iron-and-steel.com',
  'https://www.sebi.gov.in/filings/approved-option/vraj-iron-and-steel-rhp.html', 'https://linkintime.co.in/ipostatus', 240.0, 240.0, 15.9,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Bansal Wire Industries Limited (bansal-wire-industries)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Bansal Wire Industries Limited', 'bansal-wire-industries', 'Mainboard', 'Steel Wire Manufacturing', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-07-03', '2024-07-03', '2024-07-03', '2024-07-03', '2024-07-10',
  243, 256, 256, 10, 58, 99,
  '745.00', 484.25, 'NSE, BSE',
  46.5, 32.4, 18.8,
  26.5, 35.2, 36.5,
  1, 58, 14848,
  13, 754, 193024,
  14, 812, 207872,
  67, 3886, 994816,
  68, 3944, 1009664,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 3129.0,
  76.5, 64.2,
  'Bansal Wire Industries Limited is a premier operating enterprise in the Steel Wire Manufacturing sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Steel Wire Manufacturing industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@bansal-wire-industries.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@bansal-wire-industries.com', 'https://www.bansal-wire-industries.com',
  'https://www.sebi.gov.in/filings/approved-option/bansal-wire-industries-rhp.html', 'https://ris.kfintech.com/ipostatus', 356.0, 356.0, 39.0,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Emcure Pharmaceuticals Limited (emcure-pharmaceuticals)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Emcure Pharmaceuticals Limited', 'emcure-pharmaceuticals', 'Mainboard', 'Pharmaceutical Formulations', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-07-03', '2024-07-03', '2024-07-03', '2024-07-03', '2024-07-10',
  957, 1008, 1008, 10, 14, 316,
  '1952.03', 1268.82, 'NSE, BSE',
  53.5, 34.4, 15.8,
  25.5, 37.2, 35.5,
  1, 14, 14112,
  14, 196, 197568,
  15, 210, 211680,
  70, 980, 987840,
  71, 994, 1001952,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 8198.53,
  76.5, 64.2,
  'Emcure Pharmaceuticals Limited is a premier operating enterprise in the Pharmaceutical Formulations sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Pharmaceutical Formulations industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@emcure-pharmaceuticals.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@emcure-pharmaceuticals.com', 'https://www.emcure-pharmaceuticals.com',
  'https://www.sebi.gov.in/filings/approved-option/emcure-pharmaceuticals-rhp.html', 'https://linkintime.co.in/ipostatus', 1325.0, 1325.0, 31.4,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Sanstar Limited (sanstar-limited)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Sanstar Limited', 'sanstar-limited', 'Mainboard', 'Plant Ingredients', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-07-19', '2024-07-19', '2024-07-19', '2024-07-19', '2024-07-26',
  90, 95, 95, 10, 150, 13,
  '510.15', 331.6, 'NSE, BSE',
  58.5, 29.4, 20.8,
  26.5, 32.2, 30.5,
  1, 150, 14250,
  14, 2100, 199500,
  15, 2250, 213750,
  70, 10500, 997500,
  71, 10650, 1011750,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 2142.63,
  76.5, 64.2,
  'Sanstar Limited is a premier operating enterprise in the Plant Ingredients sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Plant Ingredients industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@sanstar-limited.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@sanstar-limited.com', 'https://www.sanstar-limited.com',
  'https://www.sebi.gov.in/filings/approved-option/sanstar-limited-rhp.html', 'https://ris.kfintech.com/ipostatus', 109.0, 109.0, 14.7,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Akums Drugs & Pharmaceuticals Limited (akums-drugs-and-pharmaceuticals)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Akums Drugs & Pharmaceuticals Limited', 'akums-drugs-and-pharmaceuticals', 'Mainboard', 'CDMO Pharma Manufacturing', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-07-30', '2024-07-30', '2024-07-30', '2024-07-30', '2024-08-06',
  645, 679, 679, 10, 22, 45,
  '1856.74', 1206.88, 'NSE, BSE',
  47.5, 33.4, 19.8,
  27.5, 36.2, 31.5,
  1, 22, 14938,
  13, 286, 194194,
  14, 308, 209132,
  66, 1452, 985908,
  67, 1474, 1000846,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 7798.31,
  76.5, 64.2,
  'Akums Drugs & Pharmaceuticals Limited is a premier operating enterprise in the CDMO Pharma Manufacturing sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the CDMO Pharma Manufacturing industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@akums-drugs-and-pharmaceuticals.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@akums-drugs-and-pharmaceuticals.com', 'https://www.akums-drugs-and-pharmaceuticals.com',
  'https://www.sebi.gov.in/filings/approved-option/akums-drugs-and-pharmaceuticals-rhp.html', 'https://linkintime.co.in/ipostatus', 725.0, 725.0, 6.77,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Ceigall India Limited (ceigall-india)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Ceigall India Limited', 'ceigall-india', 'Mainboard', 'Infrastructure Contracting', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-08-01', '2024-08-01', '2024-08-01', '2024-08-01', '2024-08-08',
  380, 401, 401, 10, 37, 23,
  '1252.66', 814.23, 'NSE, BSE',
  61.5, 42.4, 23.8,
  33.5, 45.2, 37.5,
  1, 37, 14837,
  13, 481, 192881,
  14, 518, 207718,
  67, 2479, 994079,
  68, 2516, 1008916,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 5261.17,
  76.5, 64.2,
  'Ceigall India Limited is a premier operating enterprise in the Infrastructure Contracting sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the Infrastructure Contracting industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'Link Intime India Private Ltd', '+91-22-4918-6270', 'ipo.help@ceigall-india.com', 'https://linkintime.co.in',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@ceigall-india.com', 'https://www.ceigall-india.com',
  'https://www.sebi.gov.in/filings/approved-option/ceigall-india-rhp.html', 'https://linkintime.co.in/ipostatus', 425.0, 425.0, 5.98,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

-- ------------------------------------------------------------------------------
-- Ola Electric Mobility Limited (ola-electric-mobility)
-- ------------------------------------------------------------------------------
INSERT INTO public.ipos (
  name, slug, ipo_type, sector, exchange, status, allotment_out, allotment_status,
  open_date, close_date, allotment_date, refund_date, listing_date,
  price_min, price_max, issue_price, face_value, lot_size, gmp,
  issue_size, fresh_issue, listing_exchange,
  sub_qib, sub_nii, sub_rii, sub_shni, sub_bhni, sub_total,
  retail_min_lots, retail_min_shares, retail_min_amount,
  retail_max_lots, retail_max_shares, retail_max_amount,
  shni_lots, shni_shares, shni_amount,
  shni_max_lots, shni_max_shares, shni_max_amount,
  bhni_lots, bhni_shares, bhni_amount,
  reservation_qib, reservation_nii, reservation_rii,
  eps_pre, eps_post, pe_pre, pe_post, roce, ronw, debt_equity, pat_margin, market_cap,
  promoter_holding_pre, promoter_holding_post,
  about_company, objectives, company_strengths, company_risks,
  lead_managers, registrar, registrar_phone, registrar_email, registrar_website,
  company_address, company_phone, company_email, company_website,
  rhp_link, allotment_link, listing_price, listing_price_open, listing_gain_percent,
  created_at, updated_at
) VALUES (
  'Ola Electric Mobility Limited', 'ola-electric-mobility', 'Mainboard', 'EV Manufacturing & Tech', 'NSE, BSE', 'Listed', TRUE, 'out',
  '2024-08-02', '2024-08-02', '2024-08-02', '2024-08-02', '2024-08-09',
  72, 76, 76, 10, 197, 0,
  '6145.56', 3994.61, 'NSE, BSE',
  60.5, 36.4, 22.8,
  24.5, 39.2, 28.5,
  1, 197, 14972,
  13, 2561, 194636,
  14, 2758, 209608,
  66, 13002, 988152,
  67, 13199, 1003124,
  '50%', '15%', '35%',
  14.2, 11.8, 22.5, 25.8, 18.2, 21.4, 0.25, 12.5, 25811.35,
  76.5, 64.2,
  'Ola Electric Mobility Limited is a premier operating enterprise in the EV Manufacturing & Tech sector serving clients across India.',
  E'1. Capital expenditure for strategic expansion.
2. Working capital requirements.
3. General corporate purposes.',
  E'• Market leadership in the EV Manufacturing & Tech industry.
• Strong balance sheet with experienced executive leadership.',
  '• Subject to macroeconomic market demand cycles and sector regulatory updates.',
  'Kotak Mahindra Capital, Axis Capital, ICICI Securities', 'KFin Technologies Limited', '+91-40-6716-2222', 'ipo.help@ola-electric-mobility.com', 'https://ris.kfintech.com',
  'Registered Corporate Office, Industrial Complex, India', '+91-22-6000-8000', 'investor@ola-electric-mobility.com', 'https://www.ola-electric-mobility.com',
  'https://www.sebi.gov.in/filings/approved-option/ola-electric-mobility-rhp.html', 'https://ris.kfintech.com/ipostatus', 76.0, 76.0, 0.0,
  NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  ipo_type = EXCLUDED.ipo_type,
  sector = EXCLUDED.sector,
  exchange = EXCLUDED.exchange,
  status = EXCLUDED.status,
  allotment_out = EXCLUDED.allotment_out,
  allotment_status = EXCLUDED.allotment_status,
  open_date = EXCLUDED.open_date,
  close_date = EXCLUDED.close_date,
  allotment_date = EXCLUDED.allotment_date,
  refund_date = EXCLUDED.refund_date,
  listing_date = EXCLUDED.listing_date,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  issue_price = EXCLUDED.issue_price,
  face_value = EXCLUDED.face_value,
  lot_size = EXCLUDED.lot_size,
  gmp = EXCLUDED.gmp,
  issue_size = EXCLUDED.issue_size,
  fresh_issue = EXCLUDED.fresh_issue,
  listing_exchange = EXCLUDED.listing_exchange,
  sub_qib = EXCLUDED.sub_qib,
  sub_nii = EXCLUDED.sub_nii,
  sub_rii = EXCLUDED.sub_rii,
  sub_shni = EXCLUDED.sub_shni,
  sub_bhni = EXCLUDED.sub_bhni,
  sub_total = EXCLUDED.sub_total,
  retail_min_lots = EXCLUDED.retail_min_lots,
  retail_min_shares = EXCLUDED.retail_min_shares,
  retail_min_amount = EXCLUDED.retail_min_amount,
  retail_max_lots = EXCLUDED.retail_max_lots,
  retail_max_shares = EXCLUDED.retail_max_shares,
  retail_max_amount = EXCLUDED.retail_max_amount,
  shni_lots = EXCLUDED.shni_lots,
  shni_shares = EXCLUDED.shni_shares,
  shni_amount = EXCLUDED.shni_amount,
  shni_max_lots = EXCLUDED.shni_max_lots,
  shni_max_shares = EXCLUDED.shni_max_shares,
  shni_max_amount = EXCLUDED.shni_max_amount,
  bhni_lots = EXCLUDED.bhni_lots,
  bhni_shares = EXCLUDED.bhni_shares,
  bhni_amount = EXCLUDED.bhni_amount,
  reservation_qib = EXCLUDED.reservation_qib,
  reservation_nii = EXCLUDED.reservation_nii,
  reservation_rii = EXCLUDED.reservation_rii,
  eps_pre = EXCLUDED.eps_pre,
  eps_post = EXCLUDED.eps_post,
  pe_pre = EXCLUDED.pe_pre,
  pe_post = EXCLUDED.pe_post,
  roce = EXCLUDED.roce,
  ronw = EXCLUDED.ronw,
  debt_equity = EXCLUDED.debt_equity,
  pat_margin = EXCLUDED.pat_margin,
  market_cap = EXCLUDED.market_cap,
  promoter_holding_pre = EXCLUDED.promoter_holding_pre,
  promoter_holding_post = EXCLUDED.promoter_holding_post,
  about_company = EXCLUDED.about_company,
  objectives = EXCLUDED.objectives,
  company_strengths = EXCLUDED.company_strengths,
  company_risks = EXCLUDED.company_risks,
  lead_managers = EXCLUDED.lead_managers,
  registrar = EXCLUDED.registrar,
  registrar_phone = EXCLUDED.registrar_phone,
  registrar_email = EXCLUDED.registrar_email,
  registrar_website = EXCLUDED.registrar_website,
  company_address = EXCLUDED.company_address,
  company_phone = EXCLUDED.company_phone,
  company_email = EXCLUDED.company_email,
  company_website = EXCLUDED.company_website,
  rhp_link = EXCLUDED.rhp_link,
  allotment_link = EXCLUDED.allotment_link,
  listing_price = EXCLUDED.listing_price,
  listing_price_open = EXCLUDED.listing_price_open,
  listing_gain_percent = EXCLUDED.listing_gain_percent,
  updated_at = NOW();

